# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site.
# These values are expected to rarely change. If you are editing this file
# very often, consider using Jekyll's data files feature.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
#
# https://jekyllrb.com/docs/configuration/
title: QUnit
description: "The powerful, easy-to-use JavaScript testing framework."
url: "https://qunitjs.com"
baseurl: ""
# This a custom theme so the native Jekyll theme system is ignored.
# But, we use github-pages which has a default theme of 'primer'.
# This is a problem because, even if we ignore its output file,
# the combination of Jekyll/Sass/Primer has compile errors:
# - https://github.com/jekyll/jekyll/issues/7426
# - https://github.com/jekyll/jekyll/issues/4268
# - https://github.com/sindresorhus/gulp-ruby-sass/issues/232
# Workaround by disabling this. – https://github.com/github/pages-gem/issues/613
theme: null

plugins:
  # https://help.github.com/articles/redirects-on-github-pages/
  - jekyll-redirect-from

# Theme
remote_theme: https://github.com/qunitjs/jekyll-theme-amethyst@ccf21c0
amethyst:
  header_logo:
    src: /img/logo-with-colored-text.svg
    width: 250
    height: 72
  twitter: qunitjs
  github: qunitjs
  gitter: qunitjs/qunit
  algolia:
    search_only_api_key: aed00982db05bd21dd05310be057bda8
    sources:
      - index: qunitjs-api
        base: https://api.qunitjs.com
      - index: qunitjs

# Conversion
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  toc_levels: "1,2"

# Sass
# https://jekyllrb.com/docs/assets/#sassscss
sass:
  style: compressed
  sourcemap: never

# Backend search index
#
# This applies to the 'jekyll algolia' command.
# Requires the ALGOLIA_API_KEY secret environment variable.
# For an example, see <https://github.com/qunitjs/qunitjs.com>.
#
# See <https://github.com/algolia/jekyll-algolia>.
algolia:
  application_id: HOJ487LP0L
  # Which index the Travis job will create/update
  # with the content of the current Jekyll site.
  # The auth key for this is injected as secure env variable.
  index_name: qunitjs
  files_to_exclude:
    # Index destination instead of intermediary
    - guides.md

# Input files
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - CONTRIBUTING.md
  - CNAME
  - vendor

# Output
permalink: title/
